"""
Report formatter for verification results.
"""

from datetime import datetime
from pathlib import Path
from typing import Optional

from ...application.usecases.run_verification import VerificationReport
from ...domain.value_objects.verdict import ValidationStatus, Verdict


class ReportFormatter:
    """Generate formatted reports from verification results."""

    def __init__(self, output_dir: Optional[Path] = None):
        self.output_dir = output_dir or Path("./reports")
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def to_markdown(self, report: VerificationReport, save: bool = True) -> str:
        """Generate a Markdown report."""
        lines = [
            "# Spec2TestBench - Verification Report",
            "",
            f"**Circuit:** `{report.circuit_name}`",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Overall Verdict:** {self._verdict_badge(report.overall_verdict)}",
            f"**Success Rate:** {report.success_rate * 100:.1f}%",
            f"**Compliance Score:** {report.compliance_score:.3f}",
            f"**Nominal Compliance:** {report.nominal_compliance_score:.3f}",
            f"**PVT Compliance:** {report.pvt_compliance_score:.3f}",
            "",
            "## Summary",
            "",
            self._summary_table(report),
            "",
            "## Detailed Results",
            "",
            self._results_table(report),
        ]

        if report.waveform_analyses:
            lines.extend(["", "## Waveform Analysis", ""])
            for waveform in report.waveform_analyses:
                lines.extend(
                    [
                        f"### {waveform.test_name}",
                        "",
                        f"**Status:** {waveform.verdict.value}",
                        f"**Confidence:** {waveform.confidence:.1%}",
                        "",
                        f"**Diagnosis:** {waveform.diagnosis}",
                        "",
                    ]
                )
                if waveform.recommendations:
                    lines.extend(["**Recommendations:**", ""])
                    for recommendation in waveform.recommendations:
                        lines.append(f"- {recommendation}")
                    lines.append("")

        recommendations = self._collect_recommendations(report)
        if recommendations:
            lines.extend(["", "## Recommendations", ""])
            for recommendation in recommendations:
                lines.append(f"- {recommendation}")

        lines.extend(["", "---", "*Report generated by Spec2TestBench v0.1.0*"])
        content = "\n".join(lines)

        if save:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filepath = self.output_dir / f"{report.circuit_name}_{timestamp}.md"
            filepath.write_text(content, encoding="utf-8")
            print(f"Report saved to {filepath}")

        return content

    def to_json(self, report: VerificationReport, save: bool = True) -> str:
        """Generate a JSON report."""
        import json

        data = {
            "circuit_name": report.circuit_name,
            "timestamp": report.timestamp,
            "overall_verdict": report.overall_verdict.value,
            "success_rate": report.success_rate,
            "compliance_score": report.compliance_score,
            "nominal_compliance_score": report.nominal_compliance_score,
            "pvt_compliance_score": report.pvt_compliance_score,
            "testbench_generation_success": report.testbench_generation_success,
            "simulation_success": report.simulation_success,
            "metrics": [
                {
                    "name": result.test_name,
                    "verdict": result.verdict.value,
                    "measured": result.measured_value,
                    "expected_min": result.expected_min,
                    "expected_max": result.expected_max,
                    "unit": result.unit,
                    "message": result.message,
                }
                for result in report.spec_results
            ],
            "waveform_analyses": [
                {
                    "test_name": waveform.test_name,
                    "verdict": waveform.verdict.value,
                    "diagnosis": waveform.diagnosis,
                    "recommendations": waveform.recommendations,
                    "confidence": waveform.confidence,
                }
                for waveform in report.waveform_analyses
            ],
            "errors": report.errors,
        }

        content = json.dumps(data, indent=2)

        if save:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filepath = self.output_dir / f"{report.circuit_name}_{timestamp}.json"
            filepath.write_text(content, encoding="utf-8")
            print(f"JSON report saved to {filepath}")

        return content

    def to_console(self, report: VerificationReport) -> str:
        """Generate console-friendly output."""
        lines = [
            "=" * 70,
            f"  Spec2TestBench - {report.circuit_name}",
            "=" * 70,
            f"\n  Overall: {report.overall_verdict.value}",
            f"  Success Rate: {report.success_rate * 100:.1f}%",
            f"  Compliance Score: {report.compliance_score:.3f}",
            f"  Nominal Compliance: {report.nominal_compliance_score:.3f}",
            f"  PVT Compliance: {report.pvt_compliance_score:.3f}",
            "",
            "  Results:",
        ]

        for result in report.spec_results:
            lines.append(
                f"    {result.verdict.value:12} {result.test_name}: "
                f"{result.measured_str} (expected {result.expected_range})"
            )

        if report.waveform_analyses:
            lines.append("\n  Waveform Analysis:")
            for waveform in report.waveform_analyses:
                lines.append(f"    {waveform.verdict.value:12} {waveform.diagnosis[:80]}...")

        if report.errors:
            lines.append("\n  Errors:")
            for error in report.errors:
                lines.append(f"    - {error}")

        lines.append("\n" + "=" * 70)
        return "\n".join(lines)

    def _verdict_badge(self, verdict: ValidationStatus) -> str:
        """Generate Markdown badge for verdict."""
        colors = {
            ValidationStatus.FAIL: "red",
            ValidationStatus.RUN: "orange",
            ValidationStatus.PASS: "brightgreen",
            ValidationStatus.ROBUST_PASS: "blue",
        }
        color = colors.get(verdict, "lightgrey")
        label = verdict.value.replace(" ", "%20")
        return f"![Verdict](https://img.shields.io/badge/verdict-{label}-{color})"

    def _summary_table(self, report: VerificationReport) -> str:
        """Generate summary markdown table."""
        total = len(report.spec_results)
        passed = sum(1 for result in report.spec_results if result.verdict == Verdict.PASS)
        failed = sum(1 for result in report.spec_results if result.verdict == Verdict.FAIL)
        warnings = sum(1 for result in report.spec_results if result.verdict == Verdict.WARNING)
        errors = sum(1 for result in report.spec_results if result.verdict == Verdict.ERROR)

        return f"""| Metric | Count |
|--------|-------|
| Pass | {passed} |
| Fail | {failed} |
| Warning | {warnings} |
| Error | {errors} |
| **Total** | **{total}** |
| **Compliance Score** | **{report.compliance_score:.3f}** |"""

    def _results_table(self, report: VerificationReport) -> str:
        """Generate results markdown table."""
        lines = ["| Metric | Status | Measured | Expected |", "|--------|--------|----------|----------|"]
        for result in report.spec_results:
            lines.append(
                f"| {result.test_name} | {result.verdict.value} | "
                f"{result.measured_str} | {result.expected_range} |"
            )
        return "\n".join(lines)

    def _collect_recommendations(self, report: VerificationReport) -> list:
        """Collect all recommendations from analyses."""
        recommendations = []
        for waveform in report.waveform_analyses:
            recommendations.extend(waveform.recommendations)
        return list(dict.fromkeys(recommendations))
