# spec2testbench/presentation/formatters/report_formatter.py

"""
Report formatter for verification results.
"""

from pathlib import Path
from typing import Optional
from datetime import datetime

from ...application.usecases.run_verification import VerificationReport
from ...domain.value_objects.verdict import Verdict, ValidationStatus


class ReportFormatter:
    """Generate formatted reports from verification results."""
    
    def __init__(self, output_dir: Optional[Path] = None):
        """
        Initialize the report formatter.
        
        Args:
            output_dir: Directory to save reports
        """
        self.output_dir = output_dir or Path("./reports")
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def to_markdown(self, report: VerificationReport, save: bool = True) -> str:
        """
        Generate Markdown report.
        
        Args:
            report: Verification report
            save: If True, save to file
            
        Returns:
            Markdown content
        """
        lines = [
            f"# Spec2TestBench - Verification Report",
            "",
            f"**Circuit:** `{report.circuit_name}`",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Overall Verdict:** {self._verdict_badge(report.overall_verdict)}",
            f"**Success Rate:** {report.success_rate*100:.1f}%",
            f"**Compliance Score:** {report.compliance_score:.3f}",
            f"**Nominal Compliance:** {report.nominal_compliance_score:.3f}",
            f"**PVT Compliance:** {report.pvt_compliance_score:.3f}",
            "",
            "## Summary",
            "",
            self._summary_table(report),
            "",
            "## Detailed Results",
            "",
            self._results_table(report),
        ]
        
        # Add waveform analysis section
        if report.waveform_analyses:
            lines.extend([
                "",
                "## Waveform Analysis",
                "",
            ])
            for wa in report.waveform_analyses:
                lines.extend([
                    f"### {wa.test_name}",
                    "",
                    f"**Status:** {wa.verdict.emoji} {wa.verdict.value}",
                    f"**Confidence:** {wa.confidence:.1%}",
                    "",
                    f"**Diagnosis:** {wa.diagnosis}",
                    "",
                ])
                if wa.recommendations:
                    lines.extend([
                        "**Recommendations:**",
                        "",
                    ])
                    for rec in wa.recommendations:
                        lines.append(f"- {rec}")
                    lines.append("")
        
        # Add recommendations section
        recommendations = self._collect_recommendations(report)
        if recommendations:
            lines.extend([
                "",
                "## Recommendations",
                "",
            ])
            for rec in recommendations:
                lines.append(f"- {rec}")
        
        lines.extend([
            "",
            "---",
            f"*Report generated by Spec2TestBench v0.5.0*",
        ])
        
        content = "\n".join(lines)
        
        if save:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filepath = self.output_dir / f"{report.circuit_name}_{timestamp}.md"
            filepath.write_text(content, encoding="utf-8")
            print(f"Report saved to {filepath}")
        
        return content
    
    def to_json(self, report: VerificationReport, save: bool = True) -> str:
        """
        Generate JSON report.
        
        Args:
            report: Verification report
            save: If True, save to file
            
        Returns:
            JSON string
        """
        import json
        
        data = {
            "circuit_name": report.circuit_name,
            "timestamp": report.timestamp,
            "overall_verdict": report.overall_verdict.value,
            "success_rate": report.success_rate,
            "compliance_score": report.compliance_score,
            "nominal_compliance_score": report.nominal_compliance_score,
            "pvt_compliance_score": report.pvt_compliance_score,
            "testbench_generation_success": report.testbench_generation_success,
            "simulation_success": report.simulation_success,
            "metrics": [
                {
                    "name": r.test_name,
                    "verdict": r.verdict.value,
                    "measured": r.measured_value,
                    "expected_min": r.expected_min,
                    "expected_max": r.expected_max,
                    "unit": r.unit,
                    "message": r.message
                }
                for r in report.spec_results
            ],
            "waveform_analyses": [
                {
                    "test_name": wa.test_name,
                    "verdict": wa.verdict.value,
                    "diagnosis": wa.diagnosis,
                    "recommendations": wa.recommendations,
                    "confidence": wa.confidence
                }
                for wa in report.waveform_analyses
            ],
            "errors": report.errors
        }
        
        content = json.dumps(data, indent=2)
        
        if save:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filepath = self.output_dir / f"{report.circuit_name}_{timestamp}.json"
            filepath.write_text(content, encoding="utf-8")
            print(f"JSON report saved to {filepath}")
        
        return content
    
    def to_console(self, report: VerificationReport) -> str:
        """
        Generate console-friendly output.
        
        Args:
            report: Verification report
            
        Returns:
            Colored console output
        """
        lines = []
        
        # Header
        lines.append("=" * 70)
        lines.append(f"  Spec2TestBench - {report.circuit_name}")
        lines.append("=" * 70)
        
        # Overall verdict
        verdict = report.overall_verdict
        lines.append(f"\n  Overall: {verdict.colorized_with_emoji}")
        lines.append(f"  Success Rate: {report.success_rate*100:.1f}%\n")
        lines.append(f"  Compliance Score: {report.compliance_score:.3f}")
        lines.append(f"  Nominal Compliance: {report.nominal_compliance_score:.3f}")
        lines.append(f"  PVT Compliance: {report.pvt_compliance_score:.3f}\n")
        
        # Results
        lines.append("  Results:")
        for result in report.spec_results:
            status = result.verdict.colorized_with_emoji
            expected = result.expected_range
            lines.append(f"    {status:8} {result.test_name}: {result.measured_str} (expected {expected})")
        
        # Waveform diagnoses
        if report.waveform_analyses:
            lines.append("\n  Waveform Analysis:")
            for wa in report.waveform_analyses:
                lines.append(f"    {wa.verdict.emoji} {wa.diagnosis[:80]}...")
        
        # Errors
        if report.errors:
            lines.append("\n  Errors:")
            for error in report.errors:
                lines.append(f"    ❌ {error}")
        
        lines.append("\n" + "=" * 70)
        
        return "\n".join(lines)
    
    def _verdict_badge(self, verdict: ValidationStatus) -> str:
        """Generate Markdown badge for verdict."""
        colors = {
            ValidationStatus.FAIL: "red",
            ValidationStatus.RUN: "orange",
            ValidationStatus.PASS: "brightgreen",
            ValidationStatus.ROBUST_PASS: "blue",
        }
        color = colors.get(verdict, "lightgrey")
        label = verdict.value.replace(" ", "%20")
        return f"![Verdict](https://img.shields.io/badge/verdict-{label}-{color})"
    
    def _summary_table(self, report: VerificationReport) -> str:
        """Generate summary markdown table."""
        total = len(report.spec_results)
        passed = sum(1 for r in report.spec_results if r.verdict == Verdict.PASS)
        failed = sum(1 for r in report.spec_results if r.verdict == Verdict.FAIL)
        warnings = sum(1 for r in report.spec_results if r.verdict == Verdict.WARNING)
        errors = sum(1 for r in report.spec_results if r.verdict == Verdict.ERROR)
        
        return f"""| Metric | Count |
|--------|-------|
| ✅ Pass | {passed} |
| ❌ Fail | {failed} |
| ⚠️ Warning | {warnings} |
| 🔴 Error | {errors} |
| **Total** | **{total}** |
| **Compliance Score** | **{report.compliance_score:.3f}** |"""
    
    def _results_table(self, report: VerificationReport) -> str:
        """Generate results markdown table."""
        lines = ["| Metric | Status | Measured | Expected |"]
        lines.append("|--------|--------|----------|----------|")
        
        for result in report.spec_results:
            status = f"{result.verdict.emoji} {result.verdict.value}"
            measured = result.measured_str
            expected = result.expected_range
            lines.append(f"| {result.test_name} | {status} | {measured} | {expected} |")
        
        return "\n".join(lines)
    
    def _collect_recommendations(self, report: VerificationReport) -> list:
        """Collect all recommendations from analyses."""
        recommendations = []
        
        for wa in report.waveform_analyses:
            recommendations.extend(wa.recommendations)
        
        # Remove duplicates
        return list(dict.fromkeys(recommendations))
