from __future__ import annotations

from enum import Enum


class GenerationMode(str, Enum):
    DETERMINISTIC = "deterministic"
    DEEPSEEK_PLAN = "deepseek_plan"
    DEEPSEEK_REFINEMENT = "deepseek_refinement"


class LLMPlanValidationStatus(str, Enum):
    VALID = "VALID"
    INVALID_JSON = "INVALID_JSON"
    SCHEMA_ERROR = "SCHEMA_ERROR"
    CASE_ID_MISMATCH = "CASE_ID_MISMATCH"
    UNKNOWN_NODE = "UNKNOWN_NODE"
    ROLE_MISMATCH = "ROLE_MISMATCH"
    MISSING_REQUIRED_METRIC = "MISSING_REQUIRED_METRIC"
    EXTRA_UNREQUESTED_METRIC = "EXTRA_UNREQUESTED_METRIC"
    UNIT_MISMATCH = "UNIT_MISMATCH"
    ANALYSIS_MISMATCH = "ANALYSIS_MISMATCH"
    INVALID_STIMULUS = "INVALID_STIMULUS"
    INVALID_SIMULATION_RANGE = "INVALID_SIMULATION_RANGE"
    UNSUPPORTED_BACKEND = "UNSUPPORTED_BACKEND"
    VERDICT_LEAKAGE = "VERDICT_LEAKAGE"
    UNSAFE_PARAMETER = "UNSAFE_PARAMETER"


class RepairStatus(str, Enum):
    NO_REPAIR = "NO_REPAIR"
    PLAN_REPAIR = "PLAN_REPAIR"
    EXECUTION_REPAIR = "EXECUTION_REPAIR"
    METRIC_REPAIR = "METRIC_REPAIR"
    REPAIR_EXHAUSTED = "REPAIR_EXHAUSTED"


class LLMTestbenchValidityStatus(str, Enum):
    VALID = "VALID"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"
    INVALID_PLAN = "INVALID_PLAN"
    COMPILATION_FAILURE = "COMPILATION_FAILURE"
    SIMULATION_FAILURE = "SIMULATION_FAILURE"
    MEASUREMENT_FAILURE = "MEASUREMENT_FAILURE"
    SEMANTIC_FAILURE = "SEMANTIC_FAILURE"
    NOT_EVALUATED_WITH_REASON = "NOT_EVALUATED_WITH_REASON"


class PlanDeltaClassification(str, Enum):
    NO_CHANGE = "NO_CHANGE"
    SEMANTICALLY_EQUIVALENT = "SEMANTICALLY_EQUIVALENT"
    VALID_REFINEMENT = "VALID_REFINEMENT"
    INVALID_REFINEMENT = "INVALID_REFINEMENT"
