from __future__ import annotations

from dataclasses import asdict, dataclass

from ...domain.entities.testbench_plan import (
    AnalysisType,
    MeasurementBackendPreference,
    StimulusType,
)
from ...domain.value_objects.metric_semantics import (
    ACQuantityType,
    TRANSFER_GAIN_V2,
)


@dataclass(frozen=True)
class MetricDefinition:
    metric_name: str
    semantic_definition: str
    compatible_analysis_types: tuple[AnalysisType, ...]
    expected_unit: str
    required_nodes: tuple[str, ...]
    preferred_backend: MeasurementBackendPreference
    definition_version: str
    quantity_type: str | None
    measurement_expression_id: str
    required_semantic_guards: dict[str, bool]

    def to_dict(self) -> dict[str, object]:
        data = asdict(self)
        data["compatible_analysis_types"] = [item.value for item in self.compatible_analysis_types]
        data["preferred_backend"] = self.preferred_backend.value
        if isinstance(self.quantity_type, ACQuantityType):
            data["quantity_type"] = self.quantity_type.value
        return data


METRIC_DEFINITIONS: dict[str, MetricDefinition] = {
    "operating_point": MetricDefinition(
        metric_name="operating_point",
        semantic_definition="DC or operating-point output voltage at the observed output node.",
        compatible_analysis_types=(AnalysisType.OP, AnalysisType.DC),
        expected_unit="V",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.NGSPICE_MEASURE,
        definition_version="operating_point_v1",
        quantity_type=None,
        measurement_expression_id="OPERATING_POINT_VOLTAGE",
        required_semantic_guards={},
    ),
    "vout_dc": MetricDefinition(
        metric_name="vout_dc",
        semantic_definition="Alias of the DC operating-point output voltage.",
        compatible_analysis_types=(AnalysisType.OP, AnalysisType.DC),
        expected_unit="V",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.NGSPICE_MEASURE,
        definition_version="operating_point_alias_v1",
        quantity_type=None,
        measurement_expression_id="OPERATING_POINT_VOLTAGE",
        required_semantic_guards={},
    ),
    "quiescent_current": MetricDefinition(
        metric_name="quiescent_current",
        semantic_definition="Supply current measured at operating point.",
        compatible_analysis_types=(AnalysisType.OP,),
        expected_unit="A",
        required_nodes=(),
        preferred_backend=MeasurementBackendPreference.NGSPICE_MEASURE,
        definition_version="quiescent_current_v1",
        quantity_type=None,
        measurement_expression_id="QUIESCENT_CURRENT",
        required_semantic_guards={},
    ),
    "idd": MetricDefinition(
        metric_name="idd",
        semantic_definition="Alias of the quiescent supply current.",
        compatible_analysis_types=(AnalysisType.OP,),
        expected_unit="A",
        required_nodes=(),
        preferred_backend=MeasurementBackendPreference.NGSPICE_MEASURE,
        definition_version="quiescent_current_alias_v1",
        quantity_type=None,
        measurement_expression_id="QUIESCENT_CURRENT",
        required_semantic_guards={},
    ),
    "power": MetricDefinition(
        metric_name="power",
        semantic_definition="DC power inferred from supply voltage and supply current.",
        compatible_analysis_types=(AnalysisType.OP,),
        expected_unit="W",
        required_nodes=(),
        preferred_backend=MeasurementBackendPreference.NGSPICE_MEASURE,
        definition_version="power_v1",
        quantity_type=None,
        measurement_expression_id="POWER_FROM_SUPPLY_CURRENT",
        required_semantic_guards={},
    ),
    "dc_gain": MetricDefinition(
        metric_name="dc_gain",
        semantic_definition="Low-frequency voltage transfer gain defined as 20*log10(abs(Vout/Vin)).",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="dB",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version=TRANSFER_GAIN_V2,
        quantity_type=ACQuantityType.TRANSFER_GAIN_DB,
        measurement_expression_id="AC_TRANSFER_GAIN_DB",
        required_semantic_guards={
            "ac_input_exists": True,
            "ac_input_nonzero": True,
            "input_output_vectors_finite": True,
            "complex_transfer_ratio_valid": True,
        },
    ),
    "dc_gain_db": MetricDefinition(
        metric_name="dc_gain_db",
        semantic_definition="Low-frequency voltage transfer gain defined as 20*log10(abs(Vout/Vin)).",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="dB",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version=TRANSFER_GAIN_V2,
        quantity_type=ACQuantityType.TRANSFER_GAIN_DB,
        measurement_expression_id="AC_TRANSFER_GAIN_DB",
        required_semantic_guards={
            "ac_input_exists": True,
            "ac_input_nonzero": True,
            "input_output_vectors_finite": True,
            "complex_transfer_ratio_valid": True,
        },
    ),
    "absolute_output_dbv": MetricDefinition(
        metric_name="absolute_output_dbv",
        semantic_definition="Absolute output amplitude defined as 20*log10(abs(Vout)/1V).",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="dBV",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="absolute_output_dbv_v1",
        quantity_type=ACQuantityType.ABSOLUTE_OUTPUT_DBV,
        measurement_expression_id="AC_ABSOLUTE_OUTPUT_DBV",
        required_semantic_guards={"output_vector_finite": True},
    ),
    "absolute_input_dbv": MetricDefinition(
        metric_name="absolute_input_dbv",
        semantic_definition="Absolute input amplitude defined as 20*log10(abs(Vin)/1V).",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="dBV",
        required_nodes=("input",),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="absolute_input_dbv_v1",
        quantity_type=ACQuantityType.ABSOLUTE_INPUT_DBV,
        measurement_expression_id="AC_ABSOLUTE_INPUT_DBV",
        required_semantic_guards={"input_vector_finite": True},
    ),
    "transfer_magnitude_linear": MetricDefinition(
        metric_name="transfer_magnitude_linear",
        semantic_definition="Low-frequency transfer magnitude defined as abs(Vout/Vin).",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="V/V",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="transfer_magnitude_linear_v1",
        quantity_type=ACQuantityType.TRANSFER_MAGNITUDE_LINEAR,
        measurement_expression_id="AC_TRANSFER_MAGNITUDE_LINEAR",
        required_semantic_guards={
            "ac_input_exists": True,
            "ac_input_nonzero": True,
            "input_output_vectors_finite": True,
            "complex_transfer_ratio_valid": True,
        },
    ),
    "transfer_phase_deg": MetricDefinition(
        metric_name="transfer_phase_deg",
        semantic_definition="Low-frequency transfer phase defined as angle(Vout/Vin) in degrees.",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="deg",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="transfer_phase_deg_v1",
        quantity_type=ACQuantityType.TRANSFER_PHASE_DEG,
        measurement_expression_id="AC_TRANSFER_PHASE_DEG",
        required_semantic_guards={
            "ac_input_exists": True,
            "ac_input_nonzero": True,
            "input_output_vectors_finite": True,
            "complex_transfer_ratio_valid": True,
        },
    ),
    "cutoff_frequency_hz": MetricDefinition(
        metric_name="cutoff_frequency_hz",
        semantic_definition="Frequency where the output magnitude drops by 3 dB relative to the low-frequency gain.",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="Hz",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="cutoff_frequency_v1",
        quantity_type=None,
        measurement_expression_id="AC_CUTOFF_FREQUENCY_HZ",
        required_semantic_guards={"requires_ac_sweep": True},
    ),
    "bandwidth": MetricDefinition(
        metric_name="bandwidth",
        semantic_definition="Alias of the AC cutoff frequency for single-pole and comparable benchmark circuits.",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="Hz",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="bandwidth_alias_v1",
        quantity_type=None,
        measurement_expression_id="AC_CUTOFF_FREQUENCY_HZ",
        required_semantic_guards={"requires_ac_sweep": True},
    ),
    "unity_gain_frequency": MetricDefinition(
        metric_name="unity_gain_frequency",
        semantic_definition="Frequency where the magnitude of the transfer function reaches unity.",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="Hz",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.AUTO,
        definition_version="unity_gain_frequency_v1",
        quantity_type=None,
        measurement_expression_id="AC_UNITY_GAIN_FREQUENCY",
        required_semantic_guards={"requires_ac_sweep": True},
    ),
    "ugbw": MetricDefinition(
        metric_name="ugbw",
        semantic_definition="Alias of the unity-gain frequency.",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="Hz",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.AUTO,
        definition_version="unity_gain_frequency_alias_v1",
        quantity_type=None,
        measurement_expression_id="AC_UNITY_GAIN_FREQUENCY",
        required_semantic_guards={"requires_ac_sweep": True},
    ),
    "phase_margin": MetricDefinition(
        metric_name="phase_margin",
        semantic_definition="Phase margin measured near the unity-gain crossover.",
        compatible_analysis_types=(AnalysisType.AC,),
        expected_unit="deg",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.AUTO,
        definition_version="phase_margin_v1",
        quantity_type=None,
        measurement_expression_id="AC_PHASE_MARGIN",
        required_semantic_guards={"requires_ac_sweep": True},
    ),
    "slew_rate": MetricDefinition(
        metric_name="slew_rate",
        semantic_definition="Maximum absolute derivative of the output transient waveform.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="V/s",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.AUTO,
        definition_version="slew_rate_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_SLEW_RATE",
        required_semantic_guards={"requires_output_waveform": True},
    ),
    "settling_time": MetricDefinition(
        metric_name="settling_time",
        semantic_definition="Time required for the output to stay within the specified band around its final value.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="s",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.AUTO,
        definition_version="settling_time_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_SETTLING_TIME",
        required_semantic_guards={"requires_output_waveform": True},
    ),
    "propagation_delay": MetricDefinition(
        metric_name="propagation_delay",
        semantic_definition="Delay between an input transition and the corresponding output threshold crossing.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="s",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_MEASURE,
        definition_version="propagation_delay_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_PROPAGATION_DELAY",
        required_semantic_guards={"requires_input_and_output_waveforms": True},
    ),
    "propagation_delay_s": MetricDefinition(
        metric_name="propagation_delay_s",
        semantic_definition="Alias of the propagation delay in seconds.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="s",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_MEASURE,
        definition_version="propagation_delay_alias_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_PROPAGATION_DELAY",
        required_semantic_guards={"requires_input_and_output_waveforms": True},
    ),
    "frequency_hz": MetricDefinition(
        metric_name="frequency_hz",
        semantic_definition="Oscillation frequency derived from a validated transient waveform.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="Hz",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="oscillator_frequency_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_OSCILLATOR_FREQUENCY",
        required_semantic_guards={"requires_valid_oscillation": True},
    ),
    "oscillator_frequency": MetricDefinition(
        metric_name="oscillator_frequency",
        semantic_definition="Alias of oscillator frequency derived from a validated transient waveform.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="Hz",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="oscillator_frequency_alias_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_OSCILLATOR_FREQUENCY",
        required_semantic_guards={"requires_valid_oscillation": True},
    ),
    "startup_amplitude": MetricDefinition(
        metric_name="startup_amplitude",
        semantic_definition="Steady-state oscillation amplitude estimated from the transient waveform tail.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="V",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="startup_amplitude_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_STARTUP_AMPLITUDE",
        required_semantic_guards={"requires_output_waveform": True},
    ),
    "v_t_plus": MetricDefinition(
        metric_name="v_t_plus",
        semantic_definition="Input voltage at the rising output threshold crossing.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="V",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="switching_threshold_rising_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_SWITCHING_THRESHOLD_RISING",
        required_semantic_guards={"requires_input_and_output_waveforms": True},
    ),
    "v_t_minus": MetricDefinition(
        metric_name="v_t_minus",
        semantic_definition="Input voltage at the falling output threshold crossing.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="V",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="switching_threshold_falling_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_SWITCHING_THRESHOLD_FALLING",
        required_semantic_guards={"requires_input_and_output_waveforms": True},
    ),
    "hysteresis_width": MetricDefinition(
        metric_name="hysteresis_width",
        semantic_definition="Absolute difference between the rising and falling switching thresholds.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="V",
        required_nodes=("input", "output"),
        preferred_backend=MeasurementBackendPreference.NGSPICE_WRDATA,
        definition_version="hysteresis_width_v1",
        quantity_type=None,
        measurement_expression_id="TRAN_HYSTERESIS_WIDTH",
        required_semantic_guards={"requires_input_and_output_waveforms": True},
    ),
    "thd": MetricDefinition(
        metric_name="thd",
        semantic_definition="Total harmonic distortion reported as a percentage.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="%",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.AUTO,
        definition_version="thd_v1",
        quantity_type=None,
        measurement_expression_id="FOURIER_THD_PERCENT",
        required_semantic_guards={"requires_output_waveform": True},
    ),
    "thd_percent": MetricDefinition(
        metric_name="thd_percent",
        semantic_definition="Alias of total harmonic distortion percentage.",
        compatible_analysis_types=(AnalysisType.TRAN,),
        expected_unit="%",
        required_nodes=("output",),
        preferred_backend=MeasurementBackendPreference.AUTO,
        definition_version="thd_alias_v1",
        quantity_type=None,
        measurement_expression_id="FOURIER_THD_PERCENT",
        required_semantic_guards={"requires_output_waveform": True},
    ),
}


def _metric(
    metric_name: str,
    semantic_definition: str,
    analysis_type: AnalysisType,
    expected_unit: str,
    required_nodes: tuple[str, ...],
    preferred_backend: MeasurementBackendPreference,
    definition_version: str,
    measurement_expression_id: str,
    *,
    quantity_type: str | None = None,
    required_semantic_guards: dict[str, bool] | None = None,
) -> MetricDefinition:
    return MetricDefinition(
        metric_name=metric_name,
        semantic_definition=semantic_definition,
        compatible_analysis_types=(analysis_type,),
        expected_unit=expected_unit,
        required_nodes=required_nodes,
        preferred_backend=preferred_backend,
        definition_version=definition_version,
        quantity_type=quantity_type,
        measurement_expression_id=measurement_expression_id,
        required_semantic_guards=required_semantic_guards or {},
    )


METRIC_DEFINITIONS.update(
    {
        "dc_transfer_curve": _metric(
            "dc_transfer_curve",
            "Scalar summary of the DC transfer curve extracted from a deterministic input sweep.",
            AnalysisType.DC,
            "V",
            ("input", "output"),
            MeasurementBackendPreference.AUTO,
            "dc_transfer_curve_v1",
            "DC_TRANSFER_CURVE",
            required_semantic_guards={"requires_dc_sweep": True},
        ),
        "local_gain": _metric(
            "local_gain",
            "Local small-signal slope derived from the DC transfer characteristic.",
            AnalysisType.DC,
            "V/V",
            ("input", "output"),
            MeasurementBackendPreference.AUTO,
            "local_gain_v1",
            "DC_LOCAL_GAIN",
            required_semantic_guards={"requires_dc_sweep": True},
        ),
        "linear_range": _metric(
            "linear_range",
            "Input range over which the DC transfer characteristic remains approximately linear.",
            AnalysisType.DC,
            "V",
            ("input", "output"),
            MeasurementBackendPreference.AUTO,
            "linear_range_v1",
            "DC_LINEAR_RANGE",
            required_semantic_guards={"requires_dc_sweep": True},
        ),
        "selected_bias": _metric(
            "selected_bias",
            "Selected bias value returned by a deterministic coarse-to-fine bias sweep.",
            AnalysisType.DC,
            "V",
            ("bias", "output"),
            MeasurementBackendPreference.AUTO,
            "selected_bias_v1",
            "DC_SELECTED_BIAS",
            required_semantic_guards={"requires_dc_sweep": True},
        ),
        "bias_objective_score": _metric(
            "bias_objective_score",
            "Objective score assigned to the chosen operating bias point.",
            AnalysisType.DC,
            "score",
            ("bias", "output"),
            MeasurementBackendPreference.AUTO,
            "bias_objective_score_v1",
            "DC_BIAS_OBJECTIVE_SCORE",
            required_semantic_guards={"requires_dc_sweep": True},
        ),
        "gain_margin": _metric(
            "gain_margin",
            "Gain margin measured from the open-loop AC transfer function.",
            AnalysisType.AC,
            "dB",
            ("input", "output"),
            MeasurementBackendPreference.AUTO,
            "gain_margin_v1",
            "AC_GAIN_MARGIN",
            required_semantic_guards={"requires_ac_sweep": True},
        ),
        "cmrr": _metric(
            "cmrr",
            "Common-mode rejection ratio derived from differential and common-mode AC gain.",
            AnalysisType.AC,
            "dB",
            ("differential_positive", "differential_negative", "output"),
            MeasurementBackendPreference.AUTO,
            "cmrr_v1",
            "AC_CMRR_DB",
            required_semantic_guards={"requires_ac_sweep": True},
        ),
        "psrr": _metric(
            "psrr",
            "Power-supply rejection ratio derived from supply injection AC analysis.",
            AnalysisType.AC,
            "dB",
            ("supply_positive", "output"),
            MeasurementBackendPreference.AUTO,
            "psrr_v1",
            "AC_PSRR_DB",
            required_semantic_guards={"requires_ac_sweep": True},
        ),
        "input_impedance": _metric(
            "input_impedance",
            "Input impedance magnitude extracted from an AC stimulus and current probe.",
            AnalysisType.AC,
            "Ohm",
            ("input",),
            MeasurementBackendPreference.AUTO,
            "input_impedance_v1",
            "AC_INPUT_IMPEDANCE",
            required_semantic_guards={"requires_ac_sweep": True},
        ),
        "output_impedance": _metric(
            "output_impedance",
            "Output impedance magnitude extracted from an AC load probe.",
            AnalysisType.AC,
            "Ohm",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "output_impedance_v1",
            "AC_OUTPUT_IMPEDANCE",
            required_semantic_guards={"requires_ac_sweep": True},
        ),
        "overshoot": _metric(
            "overshoot",
            "Step-response overshoot measured as a percentage above final value.",
            AnalysisType.TRAN,
            "%",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "overshoot_v1",
            "TRAN_OVERSHOOT_PERCENT",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "sine_response_amplitude": _metric(
            "sine_response_amplitude",
            "Steady-state sine-wave output amplitude measured in the time domain.",
            AnalysisType.TRAN,
            "V",
            ("input", "output"),
            MeasurementBackendPreference.AUTO,
            "sine_response_amplitude_v1",
            "TRAN_SINE_AMPLITUDE",
            required_semantic_guards={"requires_input_and_output_waveforms": True},
        ),
        "sine_response_phase": _metric(
            "sine_response_phase",
            "Steady-state sine-wave phase shift between input and output in degrees.",
            AnalysisType.TRAN,
            "deg",
            ("input", "output"),
            MeasurementBackendPreference.AUTO,
            "sine_response_phase_v1",
            "TRAN_SINE_PHASE_DEG",
            required_semantic_guards={"requires_input_and_output_waveforms": True},
        ),
        "rise_time": _metric(
            "rise_time",
            "10-90 percent rise time of the observed output waveform.",
            AnalysisType.TRAN,
            "s",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "rise_time_v1",
            "TRAN_RISE_TIME",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "fall_time": _metric(
            "fall_time",
            "90-10 percent fall time of the observed output waveform.",
            AnalysisType.TRAN,
            "s",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "fall_time_v1",
            "TRAN_FALL_TIME",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "ringing": _metric(
            "ringing",
            "Post-transition ringing amplitude expressed as a percentage of step amplitude.",
            AnalysisType.TRAN,
            "%",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "ringing_v1",
            "TRAN_RINGING_PERCENT",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "oscillation_detected": _metric(
            "oscillation_detected",
            "Binary oscillation-detection score where 1 means valid sustained oscillation.",
            AnalysisType.TRAN,
            "score",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "oscillation_detected_v1",
            "TRAN_OSCILLATION_DETECTED",
            required_semantic_guards={"requires_valid_oscillation": True},
        ),
        "integrator_ramp_slope": _metric(
            "integrator_ramp_slope",
            "Slope of the integrator ramp extracted from the transient response.",
            AnalysisType.TRAN,
            "V/s",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "integrator_ramp_slope_v1",
            "TRAN_INTEGRATOR_RAMP_SLOPE",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "integrator_linearity": _metric(
            "integrator_linearity",
            "Linearity score of the integrator ramp based on a fitted line.",
            AnalysisType.TRAN,
            "score",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "integrator_linearity_v1",
            "TRAN_INTEGRATOR_LINEARITY",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "differentiator_peak": _metric(
            "differentiator_peak",
            "Peak absolute value of the differentiator impulse response.",
            AnalysisType.TRAN,
            "V",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "differentiator_peak_v1",
            "TRAN_DIFFERENTIATOR_PEAK",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "differentiator_pulse_width": _metric(
            "differentiator_pulse_width",
            "Effective pulse width of the differentiator response measured at half peak.",
            AnalysisType.TRAN,
            "s",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "differentiator_pulse_width_v1",
            "TRAN_DIFFERENTIATOR_PULSE_WIDTH",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "fundamental_frequency": _metric(
            "fundamental_frequency",
            "Dominant spectral fundamental frequency derived from FFT or transient oscillation analysis.",
            AnalysisType.TRAN,
            "Hz",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "fundamental_frequency_v1",
            "FOURIER_FUNDAMENTAL_FREQUENCY",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "sfdr": _metric(
            "sfdr",
            "Spurious-free dynamic range extracted from the output spectrum.",
            AnalysisType.TRAN,
            "dB",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "sfdr_v1",
            "FOURIER_SFDR_DB",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "conversion_gain": _metric(
            "conversion_gain",
            "Mixer conversion gain between input tone amplitude and converted output tone amplitude.",
            AnalysisType.TRAN,
            "dB",
            ("input", "reference", "output"),
            MeasurementBackendPreference.AUTO,
            "conversion_gain_v1",
            "FOURIER_CONVERSION_GAIN_DB",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "spurious_components": _metric(
            "spurious_components",
            "Largest non-fundamental spectral spur amplitude expressed in dBc.",
            AnalysisType.TRAN,
            "dBc",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "spurious_components_v1",
            "FOURIER_SPUR_MAX_DBC",
            required_semantic_guards={"requires_output_waveform": True},
        ),
        "input_common_mode_range": _metric(
            "input_common_mode_range",
            "Range of common-mode input voltage over which the circuit remains valid.",
            AnalysisType.DC,
            "V",
            ("common_mode", "output"),
            MeasurementBackendPreference.AUTO,
            "input_common_mode_range_v1",
            "DC_INPUT_COMMON_MODE_RANGE",
            required_semantic_guards={"requires_dc_sweep": True},
        ),
        "differential_gain": _metric(
            "differential_gain",
            "Differential voltage gain measured from a differential AC stimulus.",
            AnalysisType.AC,
            "dB",
            ("differential_positive", "differential_negative", "output"),
            MeasurementBackendPreference.AUTO,
            "differential_gain_v1",
            "AC_DIFFERENTIAL_GAIN_DB",
            required_semantic_guards={"requires_ac_sweep": True},
        ),
        "differential_phase": _metric(
            "differential_phase",
            "Differential transfer phase measured from a differential AC stimulus.",
            AnalysisType.AC,
            "deg",
            ("differential_positive", "differential_negative", "output"),
            MeasurementBackendPreference.AUTO,
            "differential_phase_v1",
            "AC_DIFFERENTIAL_PHASE_DEG",
            required_semantic_guards={"requires_ac_sweep": True},
        ),
        "current_mirror_matching_error": _metric(
            "current_mirror_matching_error",
            "Relative current mismatch between reference and mirrored branches.",
            AnalysisType.DC,
            "ratio",
            ("current_probe",),
            MeasurementBackendPreference.AUTO,
            "current_mirror_matching_error_v1",
            "DC_CURRENT_MIRROR_MATCHING_ERROR",
            required_semantic_guards={"requires_dc_sweep": True},
        ),
        "pvt_dc_gain_variation": _metric(
            "pvt_dc_gain_variation",
            "Spread of DC gain observed across the configured PVT sweep.",
            AnalysisType.DC,
            "dB",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "pvt_dc_gain_variation_v1",
            "PVT_DC_GAIN_VARIATION",
        ),
        "pvt_vout_variation": _metric(
            "pvt_vout_variation",
            "Spread of operating-point output voltage observed across the configured PVT sweep.",
            AnalysisType.DC,
            "V",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "pvt_vout_variation_v1",
            "PVT_VOUT_VARIATION",
        ),
        "pvt_power_variation": _metric(
            "pvt_power_variation",
            "Spread of quiescent power observed across the configured PVT sweep.",
            AnalysisType.DC,
            "W",
            (),
            MeasurementBackendPreference.AUTO,
            "pvt_power_variation_v1",
            "PVT_POWER_VARIATION",
        ),
        "pvt_frequency_variation": _metric(
            "pvt_frequency_variation",
            "Spread of frequency observed across the configured PVT sweep.",
            AnalysisType.TRAN,
            "Hz",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "pvt_frequency_variation_v1",
            "PVT_FREQUENCY_VARIATION",
        ),
        "pvt_delay_variation": _metric(
            "pvt_delay_variation",
            "Spread of propagation delay observed across the configured PVT sweep.",
            AnalysisType.TRAN,
            "s",
            ("input", "output"),
            MeasurementBackendPreference.AUTO,
            "pvt_delay_variation_v1",
            "PVT_DELAY_VARIATION",
        ),
        "pvt_thd_variation": _metric(
            "pvt_thd_variation",
            "Spread of total harmonic distortion observed across the configured PVT sweep.",
            AnalysisType.TRAN,
            "%",
            ("output",),
            MeasurementBackendPreference.AUTO,
            "pvt_thd_variation_v1",
            "PVT_THD_VARIATION",
        ),
    }
)


# ACP-28 benchmark semantic metrics. These are waveform-derived and keep the
# DUT immutable; they encode the functional pass conditions used by the
# upstream benchmark without letting the LLM invent a scalar result.
METRIC_DEFINITIONS.update({
    "inverter_low_input_output_v": _metric(
        "inverter_low_input_output_v", "Output voltage at the low-input endpoint of a DC transfer sweep.",
        AnalysisType.DC, "V", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_inverter_low_input_v1", "ACP_INVERTER_LOW_INPUT_OUTPUT"),
    "inverter_high_input_output_v": _metric(
        "inverter_high_input_output_v", "Output voltage at the high-input endpoint of a DC transfer sweep.",
        AnalysisType.DC, "V", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_inverter_high_input_v1", "ACP_INVERTER_HIGH_INPUT_OUTPUT"),
    "comparator_output_separation_v": _metric(
        "comparator_output_separation_v", "Separation between mean comparator output below and above the reference region.",
        AnalysisType.DC, "V", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_comparator_separation_v1", "ACP_COMPARATOR_OUTPUT_SEPARATION"),
    "comparator_monotonicity_percent": _metric(
        "comparator_monotonicity_percent", "Percentage of DC-sweep steps consistent with increasing comparator output within 0.1 V tolerance.",
        AnalysisType.DC, "%", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_comparator_monotonicity_v1", "ACP_COMPARATOR_MONOTONICITY"),
    "current_stability_delta_a": _metric(
        "current_stability_delta_a", "Peak-to-peak current variation over a deterministic DC compliance sweep.",
        AnalysisType.DC, "A", (), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_current_stability_v1", "ACP_CURRENT_STABILITY_DELTA"),
})

METRIC_DEFINITIONS.update({
    "lowpass_attenuation_db": _metric(
        "lowpass_attenuation_db", "Low-to-high frequency attenuation over the ACP AC sweep.",
        AnalysisType.AC, "dB", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_lowpass_attenuation_v1", "ACP_LOWPASS_ATTENUATION", required_semantic_guards={"requires_ac_sweep": True}),
    "lowpass_monotonicity_percent": _metric(
        "lowpass_monotonicity_percent", "Percentage of adjacent AC samples that do not rise by more than 0.5 dB.",
        AnalysisType.AC, "%", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_lowpass_monotonicity_v1", "ACP_LOWPASS_MONOTONICITY", required_semantic_guards={"requires_ac_sweep": True}),
    "highpass_attenuation_db": _metric(
        "highpass_attenuation_db", "High-to-low frequency attenuation over the ACP AC sweep.",
        AnalysisType.AC, "dB", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_highpass_attenuation_v1", "ACP_HIGHPASS_ATTENUATION", required_semantic_guards={"requires_ac_sweep": True}),
    "highpass_monotonicity_percent": _metric(
        "highpass_monotonicity_percent", "Percentage of adjacent AC samples that do not fall by more than 0.5 dB.",
        AnalysisType.AC, "%", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_highpass_monotonicity_v1", "ACP_HIGHPASS_MONOTONICITY", required_semantic_guards={"requires_ac_sweep": True}),
    "bandpass_peak_separation_db": _metric(
        "bandpass_peak_separation_db", "Minimum separation between the pass-band peak and the mean response on each side.",
        AnalysisType.AC, "dB", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_bandpass_peak_separation_v1", "ACP_BANDPASS_PEAK_SEPARATION", required_semantic_guards={"requires_ac_sweep": True}),
    "bandstop_notch_depth_db": _metric(
        "bandstop_notch_depth_db", "Minimum separation between the notch and the mean response on each side.",
        AnalysisType.AC, "dB", ("input", "output"), MeasurementBackendPreference.NGSPICE_WRDATA,
        "acp_bandstop_notch_depth_v1", "ACP_BANDSTOP_NOTCH_DEPTH", required_semantic_guards={"requires_ac_sweep": True}),
    "output_swing_v": _metric(
        "output_swing_v", "Peak-to-peak output voltage from the selected transient/DC waveform.",
        AnalysisType.TRAN, "V", ("output",), MeasurementBackendPreference.NGSPICE_WRDATA,
        "output_swing_v1", "OUTPUT_SWING_V", required_semantic_guards={"requires_output_waveform": True}),
    "oscillation_period_cv": _metric(
        "oscillation_period_cv", "Coefficient of variation of steady-state oscillation periods.",
        AnalysisType.TRAN, "ratio", ("output",), MeasurementBackendPreference.NGSPICE_WRDATA,
        "oscillation_period_cv_v1", "OSCILLATION_PERIOD_CV", required_semantic_guards={"requires_output_waveform": True}),
    "oscillation_cycle_count": _metric(
        "oscillation_cycle_count", "Number of steady-state cycles inferred from rising mean crossings.",
        AnalysisType.TRAN, "count", ("output",), MeasurementBackendPreference.NGSPICE_WRDATA,
        "oscillation_cycle_count_v1", "OSCILLATION_CYCLE_COUNT", required_semantic_guards={"requires_output_waveform": True}),
})


ANALYSIS_BY_METRIC = {
    metric_name: definition.compatible_analysis_types[0]
    for metric_name, definition in METRIC_DEFINITIONS.items()
}


SUPPORTED_STIMULUS_TYPES: tuple[StimulusType, ...] = (
    StimulusType.DC,
    StimulusType.AC,
    StimulusType.PULSE,
    StimulusType.SIN,
    StimulusType.PWL,
    StimulusType.TRIANGLE,
)


def get_metric_definition(metric_name: str) -> MetricDefinition | None:
    return METRIC_DEFINITIONS.get(metric_name)


def require_metric_definition(metric_name: str) -> MetricDefinition:
    definition = get_metric_definition(metric_name)
    if definition is None:
        raise KeyError(f"Unsupported metric definition: {metric_name}")
    return definition
